version: 1.2
workflows:
   - name: "STAR-build-index"
     subclass: WDL
     primaryDescriptorPath: /workflows/star-build-index.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - main
         tags:
             - /.*/